// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKn_T7J4LSp0AXpiOaB-g2h08GSoNPios',
    appId: '1:427566719078:web:4dd7cec554f84050aa0da7',
    messagingSenderId: '427566719078',
    projectId: 'my-fast-pay',
    authDomain: 'my-fast-pay.firebaseapp.com',
    storageBucket: 'my-fast-pay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bZ0V0q8BeX0HekO20r5TfE1IP59xTSM',
    appId: '1:427566719078:android:6c34a173c9b395d2aa0da7',
    messagingSenderId: '427566719078',
    projectId: 'my-fast-pay',
    storageBucket: 'my-fast-pay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERkf8QqSFhG_u5de3FA5XnldnNHbwYmM',
    appId: '1:427566719078:ios:44d5f183eb424bf9aa0da7',
    messagingSenderId: '427566719078',
    projectId: 'my-fast-pay',
    storageBucket: 'my-fast-pay.appspot.com',
    iosClientId: '427566719078-ae6qdmmsjn8t9b6mkkb0rtkmb8dbtcmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fast-pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERkf8QqSFhG_u5de3FA5XnldnNHbwYmM',
    appId: '1:427566719078:ios:44d5f183eb424bf9aa0da7',
    messagingSenderId: '427566719078',
    projectId: 'my-fast-pay',
    storageBucket: 'my-fast-pay.appspot.com',
    iosClientId: '427566719078-ae6qdmmsjn8t9b6mkkb0rtkmb8dbtcmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fast-pay',
  );
}
